// projects.js
export const projectList = [
  {
    filterTag: "Web_App",
    title: "GPS 트래킹 기반 아트 러닝 어플",
    description:
      "사용자의 GPS 경로를 실시간으로 추적하고 이를 예술적인 러닝 아트로 표현하는 팀 프로젝트입니다. 프론트엔드는 React, 백엔드는 NestJS로 구축하였으며, 지도 시각화에는 Kakao Map API를 활용하였습니다.",
    tag: "App",
    image: "./image/project/walkee.jpg",
    Team: true,
    rule: ["프론트엔드", "Android 적용"],
    use: ["React", "TypeScript", "Figma", "NestJS", "MYSQL", "AWS"],
    period: "2025.07.01 ~ 2025.07.24",
    etc: "walkee",
    gitUrl: "https://github.com/walkee-project/walkee",
    siteUrl: "http://walkeeapp.s3-website.ap-northeast-2.amazonaws.com",
    pptUrl: "./project_pdf/walkee_pdf.pdf",
    videoUrl: "./project_video/walkee_video.mp4",
  },
  {
    filterTag: "Web_App",
    title: "네이버웹툰 굿즈 사이트 리뉴얼",
    description:
      "nodejs를 바탕으로 카카오 알림톡과 Firebase를 활용한 푸시알림을 활용한 네이버 굿즈 사이트를 리뉴얼하였습니다.",
    tag: "Web",
    image: "./image/project/GoodPing.png",
    Team: true,
    rule: ["프론트엔드", "UI 디자인 및 구현"],
    use: ["React", "JS", "Figma", "node.js", "PostgreSQL"],
    period: "2025.06.16 ~ 2025.06.27",
    etc: "",
    gitUrl: "https://github.com/yoenheep/project",
    siteUrl: "",
    pptUrl: "./project_pdf/GoodPing_pdf.pdf",
    videoUrl: "./project_video/GoodPing_video.mp4",
  },
  {
    filterTag: "Web_App",
    title: "파일 암호화 프로그램 및 통합 관리자 서버 개발",
    description:
      "PC에서 동작하는 파일 암호화 프로그램과 그 동작을 통합 관리할 수 있는 관리자 서버를 구축하였습니다. 추가적으로, 복호화 후 재암호화까지 가능한 Atool을 개발하여 보안성을 강화했습니다.",
    tag: "Web",
    image: "./image/project/SMSproject.png",
    Team: true,
    rule: ["프론트엔드", "UI 디자인 및 구현", "Agent 프로그램 구현"],
    use: ["HTML", "JS", "PHP", "C#", "Figma", "MYSQL"],
    period: "2025.04.29 ~ 2025.06.11",
    etc: "",
    gitUrl: "https://github.com/SMSproject-team/Smsproject",
    siteUrl: "",
    pptUrl: "./project_pdf/SMSproject_pdf.pdf",
    videoUrl: "./project_video/SMSproject_video.mp4",
  },
  {
    filterTag: "Web_App",
    title: "포켓몬 도감",
    description:
      "PokeApi를 활용하여 유행했던 포켓몬 띠부띠부씰이 연상되도록 포켓몬 도감을 제작하였습니다.",
    tag: "Web",
    image: "./image/project/pokeApi.png",
    Team: false,
    rule: "all",
    use: ["React", "tailwindcss", "vite"],
    period: "2025.04.17 ~ 2025.04.25",
    etc: "",
    gitUrl: "https://github.com/yoenheep/PokemonApi",
    siteUrl: "https://spectacular-bunny-8a65e5.netlify.app/",
    pptUrl: "./project_pdf/pokeApi_pdf.pdf",
    videoUrl: "",
  },
  {
    filterTag: "Web_App",
    title: "일정관리 프로그램",
    description:
      "React를 활용하여 Todo를 제작하고, 추가로 Todo에 코멘트를 달아 추가메모를 달 수 있도록 제작하였습니다.",
    tag: "Web",
    image: "./image/project/reactTodo.png",
    Team: false,
    rule: "all",
    use: ["React", "tailwindcss", "vite"],
    period: "2025.04.10 ~ 2025.04.11",
    etc: "",
    gitUrl: "https://github.com/yoenheep/reactTodo",
    siteUrl: "https://mellifluous-lokum-a44c85.netlify.app/",
    pptUrl: "./project_pdf/reactTodo_pdf.pdf",
    videoUrl: "",
  },
  {
    filterTag: "Web_App",
    title: "아마스빈 디자인 리뉴얼",
    description:
      "아마스빈 메인페이지를 아마스빈 캐릭터를 활용하여 귀여움과 단순함을 키워드로 리뉴얼하면서 기존 메인페이지의 부족하다고 느껴지는 내용을 추가해서 넣었습니다.",
    tag: "Web",
    image: "./image/project/amasvin.png",
    Team: false,
    rule: "all",
    use: ["HTML", "Jquery", "Figma"],
    period: "2025.03.19 ~ 2025.04.02",
    etc: "",
    gitUrl: "https://github.com/yoenheep/amasvin_renewal",
    siteUrl: "",
    pptUrl: "./project_pdf/amasvin_pdf.pdf",
    videoUrl: "",
  },
  {
    filterTag: "Web_App",
    title: "펄어비스 사이트 copy",
    description:
      "펄어비스의 홈페이지를 카피하여 제작하고, 팀 소개 페이지를 디자인 및 제작하였습니다",
    tag: "Web",
    image: "./image/project/pearlabyss.png",
    Team: true,
    rule: ["메인페이지 Header", "팀 소개 페이지"],
    use: ["HTML", "JS"],
    period: "2023.03 ~ 2023.06",
    etc: "",
    gitUrl: "https://github.com/yoenheep/pearlabyss_copy",
    siteUrl: "",
    pptUrl: "./project_pdf/pearlabyss_pdf.pdf",
    videoUrl: "",
  },
  {
    filterTag: "Game",
    title: "QuizVenture",
    description:
      "횡스크롤 게임으로 몹이 내는 문제를 풀거나 싸워서 이겨서 진행가능하도록 제작하였습니다. 플레이어는 맵을 클리어하며 최종 보스를 물리치는 것이 목표가 되게끔 하였습니다.",
    tag: "게임",
    image: "./image/project/quizventure.png",
    Team: true,
    rule: ["팀장", "UIUX"],
    use: ["Unity", "C#", "Photoshop"],
    period: "2024.03 ~ 2024.11",
    etc: "",
    gitUrl: "https://github.com/yoenheep/Capston",
    siteUrl: "",
    pptUrl: "./project_pdf/quizventure_pdf.pdf",
    videoUrl: "https://www.youtube.com/embed/X_2lFTLSQZU?autoplay=1",
  },
  {
    filterTag: "Game",
    title: "ALTF4 게임 copy",
    description:
      "고난이도 중세 액션 플랫포머 게임인 ALTF4를 Unity를 활용하여 카피 제작하였습니다.",
    tag: "게임",
    image: "./image/project/altF4.png",
    Team: true,
    rule: ["UIUX"],
    use: ["Unity", "C#", "Photoshop"],
    period: "2024.08 ~ 2024.12",
    etc: "",
    gitUrl: "",
    siteUrl: "",
    pptUrl: "./project_pdf/altF4_pdf.pdf",
    videoUrl: "https://www.youtube.com/embed/gW7VAnjjbs4?autoplay=1",
  },
  {
    filterTag: "Modeling",
    title: "가고 싶은 곳 모델링",
    description:
      "팀원이 각각 휴일에 가고 싶은 곳을 주제로 모델링 후 돌다리로 이어서 제작하였습니다.",
    tag: "모델링",
    image: "./image/project/modeling.png",
    Team: true,
    rule: ["팀장", "온천", "돌다리"],
    use: ["Blender"],
    period: "2025.06 중 2주",
    etc: "",
    gitUrl: "",
    siteUrl: "",
    pptUrl: "./project_pdf/modeling_pdf.pdf",
    videoUrl: "",
  },
];
