// projects.js
export const projectList = [
  {
    filterTag: "Web_App",
    title: "포트폴리오 웹사이트",
    description: "내 소개 페이지입니다.",
    tag: "Web",
    image: "./image/project/portfolio.png",
    Team: false,
    rule: "all",
    use: ["html", "css", "js"],
    period: "2025.01.01 ~ 2025.02.01",
    etc: "",
    gitUrl: "",
    siteUrl: "https://yoenheep.github.io/Portfolio/",
    pptUrl: "",
  },
  {
    filterTag: "Game",
    title: "졸작",
    description:
      "내 소개 페이지입니다.내 소개 페이지입니다.내 소개 페이지입니다.내 소개 페이지입니다.내 소개 페이지입니다.내 소개 페이지입니다.내 소개 페이지입니다.내 소개 페이지입니다.",
    tag: "게임",
    image: "./image/favicon.png",
    Team: true,
    rule: ["팀장", "uiux"],
    use: ["html", "css"],
    period: "2025.01.01 ~ 2025.02.01",
    etc: "",
    gitUrl: "",
    siteUrl: "",
    pptUrl: "",
  },
  {
    filterTag: "Modeling",
    title: "모델링",
    description: "내 소개 페이지입니다.",
    tag: "모델링",
    image: "",
    Team: true,
    rule: "uiux",
    use: ["html", "css"],
    period: "2025.01.01 ~ 2025.02.01",
    etc: "",
    gitUrl: "",
    siteUrl: "",
    pptUrl: "",
  },
  {
    filterTag: "Web_App",
    title: "워키",
    description: "내 소개 페이지입니다.",
    tag: "App",
    image: "",
    Team: true,
    rule: "uiux",
    use: ["html", "css"],
    period: "2025.01.01 ~ 2025.02.01",
    etc: "",
    gitUrl: "",
    siteUrl: "",
    pptUrl: "",
  },
];
